export const GET_COFFEESHOPS = "GET_COFFEESHOPS";
export const COFFEESHOPS_LOADING = "COFFEESHOPS_LOADING";



export const CHECKOUT = "CHECKOUT";
export const REMOVE_ITEM = "REMOVE_ITEM";
export const ADD_ITEM = "ADD_ITEM";
